config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :recommends do
    get "place/:place", to: "recommends#by_place", as: "by_place", on: :collection
  end

  resources :item_lists do
    resources :items, only: %i[new create update destroy] do
      post :new_original_item, on: :collection
      delete "destroy_original_item/:id", action: :destroy_original_item, as: :destroy_original_item
    end
    resources :quantities, only: %i[index edit update]

    post :duplicate, on: :member
    patch :clear_checked_items, on: :member
    patch :update_position, on: :member
  end

  resources :bag_contents do
    get :search, on: :collection
  end

  resources :item_statuses, only: %i[update] do
    patch :toggle, on: :member
    patch :sort, on: :member
  end

  resource :profile, only: %i[show edit update]

  resources :bookmarks, only: %i[index create destroy]

  get "form", to: "static_pages#form", as: "inquiry_form"
  get "policy", to: "static_pages#policy", as: "privacy_policy"
  get "terms", to: "static_pages#terms", as: "terms"
  get "how_to_use", to: "static_pages#how_to_use", as: "how_to_use"

  get "images/ogp.png", to: "images#ogp", as: "images_ogp"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[top form policy terms how_to_use]
  def top
    @show_menu = false
  end

  def form; end

  def policy; end

  def terms; end

  def how_to_use; end
end

app/views/static_pages/form.html.erb
<% content_for(:title, t('.title')) %>
<div class="mx-auto flex justify-center mb-6">
  <iframe src="https://docs.google.com/forms/d/e/1FAIpQLScD3BuYwDONXZaC-duCt6KLRvgIpCG5XIybPyXcVorS4nkn4g/viewform?embedded=true" width="640" height="1200" frameborder="0" marginheight="0" marginwidth="0">
    読み込んでいます…
  </iframe>
</div>

app/views/static_pages/how_to_use.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mx-auto pt-3 p-2 md:pl-12 md:pr-8 py-24">
  <div class="flex justify-start items-center bg-base-100">
    <div class="flex items-center">
      <span class="material-symbols-outlined md:text-2xl text-primary" style="font-variation-settings: 'FILL' 1;">help</span>
      <h1 class="text-base md:text-lg font-medium ml-3"><%= t('.title') %></h1>
    </div>
  </div>
  <div class="space-y-4 md:space-y-6 mt-6">
    <div class="collapse collapse-arrow bg-base-200 dark:bg-base-200">
      <input type="checkbox" name="my-accordion-1" />
      <div class="collapse-title flex items-center">
        <span class="material-symbols-outlined md:text-2xl">lightbulb_2</span>
        <h1 class="text-sm md:text-base font-medium ml-2">マストアイテム</h1>
      </div>
      <div class="collapse-content text-xs md:text-sm">
        <p>出かける時に必ず持って行くアイテムを場所ごとに投稿できます。</p>
        <p>右下の＋ボタンを押し、投稿を作成します。</p>
      </div>
    </div>
    <div class="collapse collapse-arrow bg-base-200 dark:bg-base-200">
      <input type="checkbox" name="my-accordion-2" />
      <div class="collapse-title flex items-center">
        <span class="material-symbols-outlined md:text-2xl">work</span>
        <h1 class="text-sm md:text-base font-medium ml-2">みんなの持ち物</h1>
      </div>
      <div class="collapse-content text-xs md:text-sm">
        <p>作成した持ち物リストにタグやコメントを付け加えて投稿できます。</p>
        <p>投稿方法は、持ち物リスト ＞ リスト右上のメニュー ＞ リストを共有 をご覧ください。</p>
      </div>
    </div>
    <div class="collapse collapse-arrow bg-base-200 dark:bg-base-200">
      <input type="checkbox" name="my-accordion-3" />
      <div class="collapse-title flex items-center">
        <span class="material-symbols-outlined md:text-2xl">playlist_add</span>
        <h1 class="text-sm md:text-base font-medium ml-2">持ち物リスト</h1>
      </div>
      <div class="collapse-content">
        <div class="collapse collapse-arrow bg-base-200">
          <input type="checkbox" name="my-accordion-4" />
          <div class="collapse-title text-sm md:text-base font-medium">持ち物リスト作成</div>
          <div class="collapse-content text-xs md:text-sm">
            <p>右下の＋ボタンを押し、リスト名を入力します。</p>
          </div>
        </div>
        <div class="collapse collapse-arrow bg-base-200">
          <input type="checkbox" name="my-accordion-5" />
          <div class="collapse-title text-sm md:text-base font-medium">リスト右上のメニュー</div>
          <div class="collapse-content text-xs md:text-sm space-y-4">
            <div class="flex flex-col">
              <div class="flex items-center">
                <span class="material-symbols-outlined text-primary">edit_note</span>
                <p class="ml-2">リスト名を変更</p>
              </div>
            </div>
            <div class="flex flex-col">
              <div class="flex items-center">
                <span class="material-symbols-outlined text-primary">image</span>
                <p class="ml-2">カバー画像を設定</p>
              </div>
            </div>
            <div class="flex flex-col">
              <div class="flex items-center">
                <span class="material-symbols-outlined text-primary">content_copy</span>
                <p class="ml-2">リストを複製</p>
              </div>
            </div>
            <div class="flex flex-col">
              <div class="flex flex-col">
                <div class="flex items-center">
                  <span class="material-symbols-outlined text-primary">share</span>
                  <p class="ml-2 mb-2">リストを共有</p>
                </div>
                <p class="text-xs ml-8">タグやコメントを追加し持ち物リストを投稿すると"みんなの持ち物"に表示されます。
                  投稿を削除しても持ち物リスト自体は削除されません。</p>
                <p class="text-xs ml-8">※空の持ち物リストは共有できません。</p>
              </div>
            </div>
            <div class="flex flex-col">
              <div class="flex items-center">
                <span class="material-symbols-outlined text-primary">playlist_remove</span>
                <p class="ml-2">リストを削除</p>
              </div>
            </div>
          </div>
        </div>
        <div class="collapse collapse-arrow bg-base-200">
          <input type="checkbox" name="my-accordion-6" />
          <div class="collapse-title text-sm md:text-base font-medium">リスト内のメニュー</div>
          <div class="collapse-content text-xs md:text-sm space-y-4">
            <div class="flex flex-col">
              <div class="flex items-center">
                <span class="material-symbols-outlined text-primary">checklist</span>
                <p class="ml-2 mb-2">アイテムを編集</p>
              </div>
              <p class="text-xs ml-8">アイテムを追加・削除し、チェックを入れ"リストを保存"を押すと、持ち物リストが更新されます。</p>
            </div>
            <div class="flex flex-col">
              <div class="flex items-center">
                <span class="material-symbols-outlined text-primary">exposure_plus_1</span>
                <p class="ml-2 mb-2">アイテム数を変更</p>
              </div>
              <p class="text-xs ml-8">複数持っていきたいアイテムの数を設定すると、持ち物リストに表示されます。</p>
            </div>
            <div class="flex flex-col">
              <div class="flex items-center">
                <span class="material-symbols-outlined text-primary">refresh</span>
                <p class="ml-2 mb-2">準備済みのアイテムをクリア</p>
              </div>
              <p class="text-xs ml-8">アイテムの準備状況を元に戻します。</p>
            </div>
            <div class="flex items-center">
              <span class="material-symbols-outlined text-primary">visibility_off</span>
              <p class="ml-2">準備済みのアイテムを非表示</p>
            </div>
          </div>
        </div>
        <div class="collapse collapse-arrow bg-base-200">
          <input type="checkbox" name="my-accordion-7" />
          <div class="collapse-title text-sm md:text-base font-medium">リストの使い方</div>
          <div class="collapse-content text-xs md:text-sm">
            <p>準備したアイテムを押すことにより、ゲージのパーセントが増えていきます。100%になると準備完了です！</p>
            <p>左側のハンドルをドラッグすると順番を並び替えられます。</p>
          </div>
        </div>
      </div>
    </div>
    <div class="collapse collapse-arrow bg-base-200 dark:bg-base-200">
      <input type="checkbox" name="my-accordion-8" />
      <div class="collapse-title flex items-center">
        <span class="material-symbols-outlined md:text-2xl">bookmark</span>
        <h1 class="text-sm md:text-base font-medium ml-2">ブックマーク</h1>
      </div>
      <div class="collapse-content text-xs md:text-sm">
        <p>"マストアイテム" および "みんなの持ち物" の投稿を保存し、持ち物をブラッシュアップしましょう！</p>
      </div>
    </div>
    <div class="collapse collapse-arrow bg-base-200 dark:bg-base-200">
      <input type="checkbox" name="my-accordion-9" />
      <div class="collapse-title flex items-center">
        <span class="material-symbols-outlined md:text-2xl">person</span>
        <h1 class="text-sm md:text-base font-medium ml-2">マイページ</h1>
      </div>
      <div class="collapse-content text-xs md:text-sm">
        <p>ヘッダーのドロップダウンメニューより、アカウント名・メールアドレス・アバターを編集できます。</p>
      </div>
    </div>
    <div class="collapse collapse-arrow bg-base-200 dark:bg-base-200">
      <input type="checkbox" name="my-accordion-10" />
      <div class="collapse-title flex items-center">
        <span class="material-symbols-outlined md:text-2xl">description</span>
        <h1 class="text-sm md:text-base font-medium ml-2">その他</h1>
      </div>
        <div class="collapse-content">
          <div class="flex flex-col space-y-6">
            <%= link_to "利用規約", terms_path, class: "text-xs md:text-sm text-nowrap" %>
            <%= link_to "プライバシーポリシー", privacy_policy_path, class: "text-xs md:text-sm text-nowrap" %>
            <%= link_to "お問い合わせ", inquiry_form_path, class: "text-xs md:text-sm text-nowrap" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/policy.html.erb
<% content_for(:title, t('.title')) %>
<div class="md:mx-32 mt-4 mb-12 flex items-center justify-center">
  <div class="rounded bg-white p-7 md:p-10 dark:bg-base-200">
    <h1 class="mb-4 text-base md:text-2xl font-bold dark:text-neutral"><%= t('.title') %></h1>
    <p class="mb-6 text-xs md:text-sm leading-7 text-gray-700 dark:text-neutral">allready.jp（以下，「当社」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。</p>

    <div class="mb-6">
      <h2 class="mb-2 text-base md:text-lg font-bold dark:text-neutral">お客様から取得する情報</h2>
      <p class="mb-2 text-xs md:text-sm text-gray-700 dark:text-neutral">当社は、お客様から以下の情報を取得します。</p>
      <ul class="pl-8 list-disc text-xs md:text-sm leading-8 text-gray-700 dark:text-neutral">
        <li>氏名(ニックネームやペンネームも含む)</li>
        <li>メールアドレス</li>
        <li>写真や動画</li>
        <li>外部サービスでお客様が利用するID、その他外部サービスのプライバシー設定によりお客様が連携先に開示を認めた情報</li>
        <li>Cookie(クッキー)を用いて生成された識別情報</li>
        <li>OSが生成するID、端末の種類、端末識別子等のお客様が利用するOSや端末に関する情報</li>
        <li>当社ウェブサイトの滞在時間、入力履歴、購買履歴等の当社ウェブサイトにおけるお客様の行動履歴</li>
        <li>当社アプリの起動時間、入力履歴、購買履歴等の当社アプリの利用履歴</li>
      </ul>
    </div>

    <div class="mb-6">
      <h2 class="mb-2 text-base md:text-lg font-bold dark:text-neutral">お客様の情報を利用する目的</h2>
      <p class="mb-2 text-xs md:text-sm text-gray-700 dark:text-neutral">当社は、お客様から取得した情報を、以下の目的のために利用します。</p>
      <ul class="pl-8 list-disc text-xs md:text-sm leading-8 text-gray-700 dark:text-neutral">
        <li>当社サービスに関する登録の受付、お客様の本人確認、認証のため</li>
        <li>お客様の当社サービスの利用履歴を管理するため</li>
        <li>利用料金の決済のため</li>
        <li>当社サービスにおけるお客様の行動履歴を分析し、当社サービスの維持改善に役立てるため</li>
        <li>当社のサービスに関するご案内をするため</li>
        <li>お客様からのお問い合わせに対応するため</li>
        <li>当社の規約や法令に違反する行為に対応するため</li>
        <li>当社サービスの変更、提供中止、終了、契約解除をご連絡するため</li>
        <li>当社規約の変更等を通知するため</li>
        <li>以上の他、当社サービスの提供、維持、保護及び改善のため</li>
      </ul>
    </div>

    <div class="mb-6">
      <h2 class="mb-2 text-base md:text-lg font-bold dark:text-neutral">安全管理のために講じた措置</h2>
      <p class="mb-2 text-xs md:text-sm leading-7 text-gray-700 dark:text-neutral">当社が、お客様から取得した情報に関して安全管理のために講じた措置につきましては、末尾記載のお問い合わせ先にご連絡をいただきましたら、法令の定めに従い個別にご回答させていただきます。</p>
    </div>

    <div class="mb-6">
      <h2 class="mb-2 text-base md:text-lg font-bold dark:text-neutral">第三者提供</h2>
      <p class="text-xs md:text-sm leading-7 text-gray-700 dark:text-neutral">当社は、お客様から取得する情報のうち、個人データ（個人情報保護法第１６条第３項）に該当するものついては、あらかじめお客様の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。</p>
      <p class="mb-2 text-xs md:text-sm leading-7 text-gray-700 dark:text-neutral">但し、次の場合は除きます。</p>
      <ul class="pl-8 list-disc text-xs md:text-sm leading-8 text-gray-700 dark:text-neutral">
        <li>個人データの取扱いを外部に委託する場合</li>
        <li>当社や当社サービスが買収された場合</li>
        <li>事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</li>
        <li>その他、法律によって合法的に第三者提供が許されている場合</li>
      </ul>
    </div>

    <div class="mb-6">
      <h2 class="mb-2 text-base md:text-lg font-bold dark:text-neutral">アクセス解析ツール</h2>
      <p class="mb-2 text-xs md:text-sm leading-7 text-gray-700 dark:text-neutral">当社は、お客様のアクセス解析のために、「Googleアナリティクス」を利用しています。Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。トラフィックデータは匿名で収集されており、個人を特定するものではありません。Cookieを無効にすれば、これらの情報の収集を拒否することができます。詳しくはお使いのブラウザの設定をご確認ください。Googleアナリティクスについて、詳しくは以下からご確認ください。</p>
      <%= link_to "Googleアナリティクス利用規約（外部サイト）", "https://marketingplatform.google.com/about/analytics/terms/jp/", target: "_blank", class: "link link-primary text-xs md:text-sm dark:link-secondary" %>
    </div>

    <div class="mb-6">
      <h2 class="mb-2 text-base md:text-lg font-bold dark:text-neutral">プライバシーポリシーの変更</h2>
      <p class="text-xs md:text-sm leading-7 text-gray-700 dark:text-neutral">当社は、必要に応じて、このプライバシーポリシーの内容を変更します。この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。</p>
    </div>

    <div class="mb-8">
      <h2 class="mb-2 text-base md:text-lg font-bold dark:text-neutral">お問い合わせ</h2>
      <p class="text-xs md:text-sm leading-7 text-gray-700 dark:text-neutral">お客様の情報の開示、情報の訂正、利用停止、削除をご希望の場合は、<%= link_to "お問い合わせフォーム", inquiry_form_path, class: "link link-primary dark:link-secondary" %>よりご連絡ください。</p>
    </div>

    <div class="flex justify-end">
      <p class="text-xs md:text-sm text-gray-700 dark:text-neutral">2024年12月20日 制定</p>
    </div>
  </div>
</div>

app/views/static_pages/top.html.erb
<div class="min-h-screen flex flex-col relative bg-fixed">
  <div class="absolute inset-0 bg-cover bg-no-repeat bg-right-bottom z-0" style="background-image: url('<%= asset_path 'background.jpg' %>');"></div>

  <div class="relative z-10 flex-1 mt-16 px-7 py-10 flex flex-col gap-10 w-full md:w-1/2 dark:text-base-100 bg-opacity-90">
    <%= link_to recommends_path, class: "card shadow-xl rounded-lg md:p-3 flex flex-col w-full md:w-xl md:transition-all md:duration-300 md:hover:scale-110" do %>
      <div class="absolute inset-0 bg-gradient-to-t from-secondary to-[#F8F8F8] opacity-90 rounded-lg"></div>
      <div class="relative card-body md:space-y-6">
        <div class="flex items-center gap-4">
          <span class="material-symbols-outlined md:text-2xl">lightbulb_2</span>
          <h1 class="card-title text-sm md:text-xl">マストアイテム</h1>
        </div>
        <p class="text-xs md:text-base text-nowrap">
          かばんに必ず入れるアイテムを行き先ごとに紹介
        </p>
      </div>
    <% end %>

    <%= link_to bag_contents_path, class: "card shadow-xl rounded-lg md:p-3 flex flex-col w-full md:w-xl md:transition-all md:duration-300 md:hover:scale-110" do %>
      <div class="absolute inset-0 bg-gradient-to-t from-secondary to-[#F8F8F8] opacity-90 rounded-lg"></div>
      <div class="relative card-body md:space-y-6">
        <div class="flex items-center gap-4">
          <span class="material-symbols-outlined md:text-2xl">work</span>
          <h1 class="card-title text-sm md:text-xl">みんなの持ち物</h1>
        </div>
        <p class="text-xs md:text-base text-nowrap">
          ライフスタイルやこだわりが詰まったかばんの中身
        </p>
      </div>
    <% end %>

    <%= link_to item_lists_path, class: "card shadow-xl rounded-lg md:p-3 flex flex-col w-full md:w-xl md:transition-all md:duration-300 md:hover:scale-110" do %>
      <div class="absolute inset-0 bg-gradient-to-t from-secondary to-[#F8F8F8] opacity-90 rounded-lg"></div>
      <div class="relative card-body md:space-y-6">
        <div class="flex items-center gap-4">
          <span class="material-symbols-outlined md:text-2xl">playlist_add</span>
          <h1 class="card-title text-sm md:text-xl">持ち物リスト</h1>
        </div>
        <p class="text-xs md:text-base text-nowrap">
          行き先に合わせてカスタマイズし準備をスムーズに
        </p>
      </div>
    <% end %>
  </div>
  <footer class="z-50 bg-base-100 text-sm text-nowrap px-7 py-4 bg-opacity-80 w-full">
    <div class="flex flex-col md:flex-row md:justify-between">
      <div class="flex flex-col md:flex-row md:justify-between space-y-6 md:space-y-0">
        <%=link_to "使い方のヒント", how_to_use_path, class: "md:hidden" %>
        <%= link_to "利用規約", terms_path, class: "mr-10"  %>
        <%= link_to "プライバシーポリシー", privacy_policy_path, class: "mr-10" %>
        <%= link_to "お問い合わせ", inquiry_form_path, class: "mr-10"  %>
      </div>
      <div class="flex justify-end mt-4 md:mt-0">
        <p>© 2025 All Ready</p>
      </div>
    </div>
  </footer>
</div>