config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :recommends do
    get "place/:place", to: "recommends#by_place", as: "by_place", on: :collection
  end

  resources :item_lists do
    resources :items, only: %i[new create update destroy] do
      post :new_original_item, on: :collection
      delete "destroy_original_item/:id", action: :destroy_original_item, as: :destroy_original_item
    end
    resources :quantities, only: %i[index edit update]

    post :duplicate, on: :member
    patch :clear_checked_items, on: :member
    patch :update_position, on: :member
  end

  resources :bag_contents do
    get :search, on: :collection
  end

  resources :item_statuses, only: %i[update] do
    patch :toggle, on: :member
    patch :sort, on: :member
  end

  resource :profile, only: %i[show edit update]

  resources :bookmarks, only: %i[index create destroy]

  get "form", to: "static_pages#form", as: "inquiry_form"
  get "policy", to: "static_pages#policy", as: "privacy_policy"
  get "terms", to: "static_pages#terms", as: "terms"
  get "how_to_use", to: "static_pages#how_to_use", as: "how_to_use"

  get "images/ogp.png", to: "images#ogp", as: "images_ogp"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/views/shared/_before_login_header.html.erb
<div class="fixed top-0 z-50 flex h-16 w-full items-center md:pl-1 shadow bg-base-100 dark:shadow-neutral">
  <nav class="navbar w-full">
    <div class="flex justify-between w-full">
      <div class="flex items-center">
        <%= link_to "/", class: "btn btn-ghost flex items-center gap-4" do %>
          <%= image_tag "logo.png", class: "w-7 md:w-9 object-contain" %>
          <h1 class="text-lg md:text-xl font-bold tracking-wider">All Ready</h1>
        <% end %>
      </div>
      <div class="flex items-center gap-6 mr-4 font-bold">
        <div class="hidden md:flex items-center">
          <%=link_to how_to_use_path, class: "text-sm md:text-base flex items-center font-medium" do %>
            <span class="material-symbols-outlined">help</span>
          <% end %>
        </div>
        <div data-controller="theme" class="flex items-center">
          <label class="swap swap-rotate">
            <input type="checkbox" data-theme-target="toggle" data-action="change->theme#toggle" />
            <span class="material-symbols-outlined swap-off" id="theme-toggle-light-icon">light_mode</span>
            <span class="material-symbols-outlined swap-on" id="theme-toggle-dark-icon">dark_mode</span>
          </label>
        </div>
        <%= link_to new_user_session_path, class: "w-full px-2 md:px-4 py-2 flex items-center justify-center gap-2 transition-all ease-in duration-300 bg-white dark:bg-base-200 rounded-lg shadow-md text-sm md:text-base font-medium text-white bg-gradient-to-tl from-primary to-cyan-500 hover:bg-gradient-to-br hover:shadow-lg dark:text-neutral" do %>
          <span class="material-symbols-outlined">login</span>
          <%= t('header.login') %>
        <% end %>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="bg-sky-100 border text-sky-700 text-sm text-left rounded relative">
    <ul class="list-none pl-3">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="<%= flash_background_color(message_type) %> max-w-md mx-auto text-center text-xs border rounded-full my-4 px-4 py-2">
    <%= message %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="fixed top-0 z-50 flex h-16 w-full items-center md:pl-1 shadow bg-base-100 dark:shadow-neutral">
  <nav class="navbar w-full">
    <div class="flex justify-between w-full items-center">
      <div class="flex items-center space-x-4">
        <%= link_to "/", class: "btn btn-ghost flex items-center space-x-2 md:space-x-4" do %>
          <%= image_tag "logo.png", class: "w-7 md:w-9 object-contain" %>
          <h1 class="text-lg md:text-xl font-bold tracking-wider">All Ready</h1>
        <% end %>
      </div>
      <div class="flex items-center gap-6 mr-4 font-bold">
        <div data-controller="theme" class="flex items-center">
          <label class="swap swap-rotate">
            <input type="checkbox" data-theme-target="toggle" data-action="change->theme#toggle" />
            <span class="material-symbols-outlined swap-off" id="theme-toggle-light-icon">light_mode</span>
            <span class="material-symbols-outlined swap-on" id="theme-toggle-dark-icon">dark_mode</span>
          </label>
        </div>
        <div class="dropdown dropdown-hover dropdown-bottom dropdown-end">
          <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
            <div class="w-10 h-10 rounded-full">
              <%= image_tag current_user.avatar_url, class: "w-10 h-10 rounded-full object-cover" %>
            </div>
          </div>
          <ul tabindex="0" class="dropdown-content menu bg-slate-50 text-neutral rounded-box z-[1] w-52 md:w-64 p-2 shadow space-y-4 dark:bg-base-200 dark:text-neutral">
            <li>
              <%= link_to profile_path, class: "text-sm md:text-base flex items-center font-medium" do %>
                <span class="material-symbols-outlined mr-2">person</span>
                <%= current_user.name %>
              <% end %>
            </li>
            <li>
              <%=link_to how_to_use_path, class: "text-sm md:text-base flex items-center font-medium" do %>
                <span class="material-symbols-outlined mr-2">help</span>
                <%= t('header.how_to_use') %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "text-sm md:text-base flex items-center font-medium" do %>
                <span class="material-symbols-outlined mr-2">logout</span>
                <%= t('header.logout') %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_loading.html.erb
<div id="loading" data-loading-target="spinner" class="flex justify-center items-center fixed top-0 left-0 z-50 w-screen h-screen bg-base-100 dark:bg-base-100 transition-opacity duration-300 opacity-100">
  <div class="flex flex-col justify-center items-center">
    <%= image_tag "loading.gif", class: "w-5 md:w-7 object-contain" %>
    <p class="text-xs md:text-sm dark:text-neutral mt-2">Loading...</p>
  </div>
</div>

app/views/shared/_menu.html.erb
<aside id="default-sidebar" class="fixed left-0 w-64 z-40 h-full transition-transform md:block hidden" aria-label="Sidebar">
  <div class="h-full px-3 py-4 bg-base-200 dark:bg-base-200 dark:text-neutral">
    <ul class="space-y-6 font-medium">
      <li>
        <%= link_to recommends_path, class: "flex items-center p-4 rounded group #{request.path.start_with?('/recommends') ? 'bg-gray-200 dark:bg-[#D9D9D9] text-primary font-bold' : 'hover:bg-gray-200 dark:hover:bg-base-300 text-neutral'}", style: ("font-variation-settings: 'FILL' 1;" if request.path.start_with?('/recommends')) do %>
          <span class="material-symbols-outlined text-2xl">lightbulb_2</span>
          <span class="flex-1 ml-3 whitespace-nowrap text-base">マストアイテム</span>
        <% end %>
      </li>
      <li>
        <%= link_to bag_contents_path, class: "flex items-center p-4 rounded group #{request.path.include?('/bag_contents') ? 'bg-gray-200 dark:bg-[#D9D9D9] text-primary font-bold' : 'hover:bg-gray-200 dark:hover:bg-base-300 text-neutral'}", style: ("font-variation-settings: 'FILL' 1;" if request.path.include?('/bag_contents')) do %>
          <span class="material-symbols-outlined text-2xl">work</span>
          <span class="flex-1 ml-3 whitespace-nowrap text-base">みんなの持ち物</span>
        <% end %>
      </li>
      <li>
        <%= link_to item_lists_path, class: "flex items-center p-4 rounded group #{(request.path.start_with?('/item_lists') && !request.path.include?('/bag_contents')) ? 'bg-gray-200 dark:bg-[#D9D9D9] text-primary font-bold' : 'hover:bg-gray-200 dark:hover:bg-base-300 text-neutral'}", style: ("font-variation-settings: 'FILL' 1;" if request.path.start_with?('/item_lists')) do %>
          <span class="material-symbols-outlined text-2xl">playlist_add</span>
          <span class="flex-1 ml-3 whitespace-nowrap text-base">持ち物リスト</span>
        <% end %>
      </li>
      <li>
        <%= link_to bookmarks_path, class: "flex items-center p-4 rounded group #{request.path.include?('/bookmarks') ? 'bg-gray-200 dark:bg-[#D9D9D9] text-primary font-bold' : 'hover:bg-gray-200 dark:hover:bg-base-300 text-neutral'}", style: ("font-variation-settings: 'FILL' 1;" if request.path.include?('/bookmarks')) do %>
          <span class="material-symbols-outlined text-2xl">bookmark</span>
          <span class="flex-1 ml-3 whitespace-nowrap text-base">ブックマーク</span>
        <% end %>
      </li>
    </ul>
  </div>
</aside>

<div class="fixed bottom-0 left-0 z-50 w-full h-24 bg-base-200 border-t border-gray-200 md:hidden">
  <div class="grid h-full max-w-lg grid-cols-4 mx-auto font-medium">
    <%= link_to recommends_path, class: "inline-flex flex-col items-center justify-center px-5 group #{request.path.start_with?('/recommends') ? 'bg-gray-200 dark:bg-[#D9D9D9] text-primary font-bold' : 'hover:bg-gray-50 dark:hover:bg-base-300 text-neutral'}", style: ("font-variation-settings: 'FILL' 1;" if request.path.start_with?('/recommends')) do %>
      <span class="material-symbols-outlined text-2xl mb-2">lightbulb_2</span>
      <span class="text-[8px] text-nowrap">マストアイテム</span>
    <% end %>

    <%= link_to bag_contents_path, class: "inline-flex flex-col items-center justify-center px-5 group #{request.path.include?('/bag_contents') ? 'bg-gray-200 dark:bg-[#D9D9D9] text-primary font-bold' : 'hover:bg-gray-50 dark:hover:bg-base-300 text-neutral'}", style: ("font-variation-settings: 'FILL' 1;" if request.path.include?('/bag_contents')) do %>
      <span class="material-symbols-outlined text-2xl mb-2">work</span>
      <span class="text-[8px] text-nowrap">みんなの持ち物</span>
    <% end %>

    <%= link_to item_lists_path, class: "inline-flex flex-col items-center justify-center px-5 group #{(request.path.start_with?('/item_lists') && !request.path.include?('/bag_contents')) ? 'bg-gray-200 dark:bg-[#D9D9D9] text-primary font-bold' : 'hover:bg-gray-50 dark:hover:bg-base-300 text-neutral'}", style: ("font-variation-settings: 'FILL' 1;" if request.path.start_with?('/item_lists')) do %>
      <span class="material-symbols-outlined text-2xl mb-2">playlist_add</span>
      <span class="text-[8px] text-nowrap">持ち物リスト</span>
    <% end %>

    <%= link_to bookmarks_path, class: "inline-flex flex-col items-center justify-center px-5 group #{request.path.include?('/bookmarks') ? 'bg-gray-200 dark:bg-[#D9D9D9] text-primary font-bold' : 'hover:bg-gray-50 dark:hover:bg-base-300 text-neutral'}", style: ("font-variation-settings: 'FILL' 1;" if request.path.include?('/bookmarks')) do %>
      <span class="material-symbols-outlined text-2xl mb-2">bookmark</span>
      <span class="text-[8px] text-nowrap">ブックマーク</span>
    <% end %>
  </div>
</div>