config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :recommends do
    get "place/:place", to: "recommends#by_place", as: "by_place", on: :collection
  end

  resources :item_lists do
    resources :items, only: %i[new create update destroy] do
      post :new_original_item, on: :collection
      delete "destroy_original_item/:id", action: :destroy_original_item, as: :destroy_original_item
    end
    resources :quantities, only: %i[index edit update]

    post :duplicate, on: :member
    patch :clear_checked_items, on: :member
    patch :update_position, on: :member
  end

  resources :bag_contents do
    get :search, on: :collection
  end

  resources :item_statuses, only: %i[update] do
    patch :toggle, on: :member
    patch :sort, on: :member
  end

  resource :profile, only: %i[show edit update]

  resources :bookmarks, only: %i[index create destroy]

  get "form", to: "static_pages#form", as: "inquiry_form"
  get "policy", to: "static_pages#policy", as: "privacy_policy"
  get "terms", to: "static_pages#terms", as: "terms"
  get "how_to_use", to: "static_pages#how_to_use", as: "how_to_use"

  get "images/ogp.png", to: "images#ogp", as: "images_ogp"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/item_list.rb
class ItemList < ApplicationRecord
  belongs_to :user, primary_key: :uuid, foreign_key: :user_uuid
  has_many :item_list_original_items, dependent: :destroy
  has_many :original_items, through: :item_list_original_items
  has_many :item_list_default_items, dependent: :destroy
  has_many :default_items, through: :item_list_default_items
  has_many :item_statuses, -> { order(position: :asc) }, dependent: :destroy
  has_many :bag_contents, dependent: :destroy

  validates :name, presence: true
  validates :user_uuid, presence: true
  validates :ready_status, inclusion: { in: 0..100 }

  mount_uploader :cover_image, CoverImageUploader

  def update_ready_status
    total_selected_count = item_statuses.where(selected: true).count
    return self.update!(ready_status: 0) if total_selected_count.zero?
    checked_count = item_statuses.where(selected: true, is_checked: true).count
    ready_status = (checked_count / total_selected_count.to_f * 100).to_i
    self.update!(ready_status: ready_status)
  end

  def duplicate
    duplicated_list = ItemList.new
    duplicated_list.name = "#{self.name}のコピー"
    duplicated_list.user_uuid = self.user_uuid
    duplicated_list.ready_status = 0
    duplicated_list.cover_image = nil
    duplicated_list.save!

    self.original_items.each do |original_item|
      duplicated_original_item = original_item.dup
      duplicated_original_item.save!

      ItemListOriginalItem.create!(
        item_list: duplicated_list,
        original_item: duplicated_original_item
      )

      original_item_status = ItemStatus.find_by(item_list_id: self.id, original_item_id: original_item.id)

      if original_item_status && original_item_status.selected
        ItemStatus.create!(
          item_list_id: duplicated_list.id,
          original_item_id: duplicated_original_item.id,
          selected: original_item_status.selected,
          position: original_item_status.position
        )
      end
    end

    self.default_items.each do |default_item|
      default_item_status = ItemStatus.find_by(item_list_id: self.id, default_item_id: default_item.id)
      if default_item_status
        item_status = ItemStatus.create!(
          item_list_id: duplicated_list.id,
          default_item_id: default_item.id,
          selected: default_item_status.selected,
          position: default_item_status.position
        )
      end
    end
    duplicated_list
  end


  def clear_checked_items
    item_statuses.where(is_checked: true).update_all(is_checked: false)
    update!(ready_status: 0)
  end

  def update_position(item_ids)
    item_statuses.update_all(position: nil)

    item_ids.each_with_index do |item_id, index|
      item_status = ItemStatus.find_by(default_item_id: item_id, item_list_id: self.id) ||
                    ItemStatus.find_by(original_item_id: item_id, item_list_id: self.id)

      item_status.update(position: index + 1) if item_status
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "name" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "bag_content", "default_items", "original_items" ]
  end
end

app/controllers/item_lists_controller.rb
class ItemListsController < ApplicationController
  include ActionView::RecordIdentifier

  def index
    @item_lists = ItemList.where(user_uuid: current_user.uuid).includes(:user).order(created_at: :asc)
    @bag_contents = BagContent.all
  end

  def show
    @item_list = ItemList.find(params[:id])

    @selected_default_items = DefaultItem.joins(:item_statuses)
                                         .where(item_statuses: { item_list_id: @item_list.id, selected: true })
                                         .includes(:item_statuses)
                                         .order("item_statuses.position")

    @selected_original_items = OriginalItem.joins(:item_statuses)
                                           .where(item_statuses: { item_list_id: @item_list.id, selected: true })
                                           .includes(:item_statuses)
                                           .order("item_statuses.position")
  end

  def new
    @item_list = ItemList.new
  end

  def create
    @item_list = current_user.item_lists.build(item_list_params)
    if @item_list.save
      redirect_to item_lists_path
    else
      redirect_to item_lists_path
    end
  end

  def edit
    @item_list = current_user.item_lists.find_by(uuid: params[:id])
  end

  def update
    @item_list = ItemList.find(params[:id])

    if @item_list.update(item_list_params)
      if params[:item_list][:original_item_ids].present? || params[:item_list][:default_item_ids].present?
        @item_list.item_statuses.update_all(selected: false)

        if params[:item_list][:original_item_ids].present?
          selected_original_ids = params[:item_list][:original_item_ids].map(&:to_i)
          @item_list.original_items.each do |item|
            item_status = ItemStatus.find_or_create_by(item_list_id: @item_list.id, original_item_id: item.id)
            item_status.update(selected: selected_original_ids.include?(item.id))
          end
        end

        if params[:item_list][:default_item_ids].present?
          selected_default_ids = params[:item_list][:default_item_ids].map(&:to_i)
          @item_list.default_items.each do |item|
            item_status = ItemStatus.find_or_create_by(item_list_id: @item_list.id, default_item_id: item.id)
            item_status.update(selected: selected_default_ids.include?(item.id))
          end
        end
        # チェックボックスの変更
        redirect_to item_list_path(@item_list), notice: t("defaults.flash_message.updated", item: ItemList.model_name.human)
      else
        # リスト名、カバー画像などの変更
        redirect_to item_lists_path, notice: t("defaults.flash_message.updated", item: ItemList.model_name.human)
      end
    end
  end

  def destroy
    item_list = ItemList.find_by(user_uuid: current_user.uuid, id: params[:id])
    ItemListOriginalItem.where(item_list_id: item_list.id).destroy_all
    item_list.destroy!
    redirect_to item_lists_path, notice: t("defaults.flash_message.deleted", item: ItemList.model_name.human), status: :see_other
  end

  def duplicate
    @item_list = ItemList.find(params[:id])
    duplicated_item_list = @item_list.duplicate
    redirect_to item_lists_path
  end

  def clear_checked_items
    @item_list = ItemList.find(params[:id])
    @item_list.clear_checked_items
    @item_statuses = @item_list.item_statuses
    redirect_to item_list_path(@item_list)
  end

  def update_position
    @item_list = ItemList.find(params[:id])
    if params[:item_ids].present?
      @item_list.update_position(params[:item_ids])
      head :ok
    end
  end

  private

  def set_item_list
    @item_list = ItemList.find(params[:id])
  end

  def item_list_params
    params.require(:item_list).permit(:name, :cover_image, :cover_image_cache, original_item_ids: [], default_item_ids: [])
  end
end

app/views/item_lists/_item_list.html.erb
<% if item_list.cover_image.present? %>
  <div class="card bg-slate-50 w-40 h-40 md:w-48 md:h-48 rounded shadow relative dark:bg-base-200">
    <div class="card-title flex justify-between items-center p-2 text-sm md:text-lg w-full relative">
      <div class="flex-grow pl-2 pr-10 font-medium" style="cursor: default; word-wrap: break-word; overflow-wrap: break-word;">
        <%= item_list.name %>
      </div>
      <span class="material-symbols-outlined size-30 absolute top-1 md:top-2 right-2 md:right-3 z-10" style="cursor: pointer;" onclick="openMenuModal(<%= item_list.id %>)">more_horiz</span>
      <%= render 'item_list_modal', item_list: item_list %>
    </div>
    <figure class="w-full h-full">
      <%= link_to item_list_path(item_list), class: "w-full h-full block" do %>
        <%= image_tag item_list.cover_image.url, class: "w-full h-full object-cover object-bottom" %>
      <% end %>
    </figure>
  </div>
<% else %>
  <div class="card bg-slate-50 w-40 h-40 md:w-48 md:h-48 rounded shadow relative dark:bg-base-200">
    <div class="card-title flex justify-between items-center p-2 text-sm md:text-lg w-full relative">
      <div class="flex-grow pl-2 pr-10 font-medium" style="cursor: default; word-wrap: break-word; overflow-wrap: break-word;">
        <%= item_list.name %>
      </div>
      <span class="material-symbols-outlined size-30 absolute top-1 md:top-2 right-2 md:right-3" style="cursor: pointer;" onclick="openMenuModal(<%= item_list.id %>)">more_horiz</span>
      <%= render 'item_list_modal', item_list: item_list %>
    </div>
    <%= link_to item_list_path(item_list), class: "flex justify-center items-center w-full h-full block rounded-b-lg bg-base-200 dark:bg-base-300" do %>
      <%= image_tag "placeholder.png", class: "w-24 h-24" %>
    <% end %>
  </div>
<% end %>

app/views/item_lists/_item_list_modal.html.erb
<dialog id="menuModal_<%= item_list.id %>" class="modal">
  <div class="modal-box bg-slate-50 w-96 mx-auto px-4 dark:bg-base-200">
    <div class="p-4 flex flex-col justify-center w-full space-y-8">
      <button class="btn w-full btn-outline text-primary font-normal bg-base-100 dark:bg-base-200 dark:text-neutral border-primary dark:border-neutral hover:bg-gray-100 hover:border-primary hover:text-primary
        dark:hover:bg-base-300 dark:hover:border-neutral dark:hover:text-neutral" onclick="openRenameModal(<%= item_list.id %>)">
        <span class="material-symbols-outlined">edit_note</span>
        リスト名を変更
      </button>
      <button class="btn w-full btn-outline text-primary font-normal bg-base-100 dark:bg-base-200 dark:text-neutral border-primary dark:border-neutral hover:bg-gray-100 hover:border-primary hover:text-primary
        dark:hover:bg-base-300 dark:hover:border-neutral dark:hover:text-neutral" onclick="openCoverImageModal(<%= item_list.id %>)">
        <span class="material-symbols-outlined">image</span>
        カバー画像を設定
      </button>
      <%= form_with url: duplicate_item_list_path(item_list), method: :post, local: true, class: "w-full" do %>
        <button type="submit" class="btn w-full btn-outline text-primary font-normal bg-base-100 dark:bg-base-200 dark:text-neutral border-primary dark:border-neutral hover:bg-gray-100 hover:border-primary hover:text-primary
          dark:hover:bg-base-300 dark:hover:border-neutral dark:hover:text-neutral">
          <span class="material-symbols-outlined">content_copy</span>
          リストを複製
        </button>
      <% end %>
      <% unless current_user.bag_contents.exists?(item_list_id: item_list.id) %>
       <button class="btn w-full btn-outline text-primary font-normal bg-base-100 dark:bg-base-200 dark:text-neutral border-primary dark:border-neutral hover:bg-gray-100 hover:border-primary hover:text-primary
        dark:hover:bg-base-300 dark:hover:border-neutral dark:hover:text-neutral" onclick="openShareModal(<%= item_list.id %>)">
        <span class="material-symbols-outlined">share</span>
        リストを共有
       </button>
      <% else %>
        <% @bag_contents.each do |bag_content| %>
          <% if bag_content.item_list_id == item_list.id %>
            <%= link_to bag_content_path(bag_content.uuid), class: "btn w-full btn-primary font-normal", onclick: "document.getElementById('menuModal_#{item_list.id}').close();" do %>
              <span class="material-symbols-outlined">share</span>
              リストを共有中
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <button class="btn w-full btn-base-300 dark:btn-outline font-normal" onclick="openDeleteModal(<%= item_list.id %>)">
        <span class="material-symbols-outlined">playlist_remove</span>
        リストを削除
      </button>
      <button class="btn w-full btn-ghost font-normal" onclick="document.getElementById('menuModal_<%= item_list.id %>').close()">キャンセル</button>
    </div>
  </div>
</dialog>

<dialog id="renameModal_<%= item_list.id %>" class="modal">
  <div class="modal-box bg-slate-50 w-96 mx-auto px-4 dark:bg-base-200">
    <div class="p-4 flex flex-col justify-center w-full space-y-6">
      <%= form_with model: item_list, url: item_list_path(item_list), method: :patch, local: true, class: "w-full flex flex-col space-y-4" do |f| %>
        <label class="form-control w-full">
          <input type="text" name="item_list[name]" class="input input-bordered w-full dark:bg-base-200" value="<%= item_list.name %>" required />
        </label>
        <div class="modal-action w-full">
          <%= f.submit '決定', class: "btn w-full btn-primary" %>
        </div>
      <% end %>
      <div class="modal-action w-full">
        <button class="btn w-full btn-ghost" onclick="document.getElementById('renameModal_<%= item_list.id %>').close()">キャンセル</button>
      </div>
    </div>
  </div>
</dialog>

<dialog id="coverImageModal_<%= item_list.id %>" class="modal">
  <div class="modal-box bg-slate-50 md:w-2/3 mx-auto px-4 dark:bg-base-200">
    <div class="p-4 flex flex-col justify-center w-full space-y-6">
      <%= form_with model: item_list, url: item_list_path(item_list), method: :patch, class: "w-full", local: true do |f| %>
        <div>
          <%= f.file_field :cover_image, class: "file-input file-input-bordered file-input-primary file-input-sm w-full mt-2 mb-2 dark:file-input-secondary", accept: 'image/*' %>
          <%= f.hidden_field :cover_image_cache %>
        </div>
        <div class="flex mt-4 justify-end">
          <%= f.submit t('item_lists.new.submit_label'), class: "btn w-full btn-primary" %>
        </div>
      <% end %>
      <div class="modal-action">
        <button class="btn w-full btn-ghost" onclick="document.getElementById('coverImageModal_<%= item_list.id %>').close()">キャンセル</button>
      </div>
    </div>
  </div>
</dialog>

<dialog id="shareModal_<%= item_list.id %>" class="modal">
  <div class="modal-box bg-slate-50 md:w-2/3 mx-auto px-4 dark:bg-base-200">
    <div class="p-4 flex flex-col justify-center w-full space-y-6">
      <h2 class="text-base font-medium"><%= item_list.name %></h2>
      <%= form_with model: @bag_content, url: bag_contents_path, method: :post, local: true do |f| %>
        <%= f.hidden_field :item_list_id, value: item_list.id %>
        <div>
          <%= f.label :tag_name, "タグ　<span class='text-xs text-gray-500 dark:text-neutral'>(半角スペース区切り・3つまで)</span>".html_safe, class: "block text-sm font-medium mb-2" %>
          <%= f.text_field :tag_name, placeholder: "例：秋 温泉 食べ歩き", class: "w-full border border-gray-300 bg-slate-50 text-xs md:text-sm font-normal rounded-md shadow-sm px-3 py-2 focus:outline-none focus:ring-1 focus:ring-blue-500, placeholder:text-xs dark:bg-base-200" %>
        </div>
        <div class="mt-4">
          <%= f.label :body, "コメント", class: "block text-sm font-normal mb-2" %>
          <%= f.text_area :body, placeholder: "こだわりポイント、おすすめのアイテムなど", class: "w-full border border-gray-300 bg-slate-50 text-xs md:text-sm font-normal rounded-md shadow-sm px-3 py-2 focus:outline-none focus:ring-1 focus:ring-blue-500, placeholder:text-xs dark:bg-base-200", rows: 5 %>
        </div>
        <p class="text-xs text-accent my-4">※空の持ち物リストは共有できません</p>
        <div class="flex mt-4 justify-end">
          <%= f.submit t('bag_contents.new.submit_label'), class: "btn w-full btn-primary" %>
        </div>
      <% end %>
      <div class="modal-action">
        <button class="btn w-full btn-ghost" onclick="document.getElementById('shareModal_<%= item_list.id %>').close()">キャンセル</button>
      </div>
    </div>
  </div>
</dialog>

<dialog id="deleteModal_<%= item_list.id %>" class="modal">
  <div class="modal-box bg-slate-50 w-96 mx-auto px-4 space-y-6 dark:bg-base-200">
    <div class="text-left">
      <h3 class="font-bold text-base text-accent mb-2">リストを削除しますか？</h3>
      <p class="text-sm">リストを共有している場合、投稿も削除されます。</p>
    </div>
    <%= form_with url: item_list_path(item_list), method: :delete, class: "w-full" do |f| %>
      <button class="btn w-full btn-accent text-white font-normal" type="submit">削除する</button>
    <% end %>
    <button class="btn w-full btn-ghost font-normal" onclick="document.getElementById('deleteModal_<%= item_list.id %>').close()">キャンセル</button>
  </div>
</dialog>

app/views/item_lists/_ready_status.html.erb
<div id="<%= dom_id(item_list, :ready_status) %>" class="flex justify-end w-full">
  <div class="bg-base-200 dark:bg-base-300 rounded-full overflow-hidden h-5 md:h-7 w-full relative">
    <div class="flex flex-col justify-center rounded-full bg-gradient-to-r from-cyan-500 to-primary text-sm text-white text-center h-5 md:h-7 leading-none transition duration-500"
          style="width: <%= item_list.ready_status %>%; background-color: <%= item_list.ready_status == 0 ? 'text-primary' : 'primary' %>;">
      <%= content_tag :span, (item_list.ready_status == 100 ? 'All Ready!' : item_list.ready_status.to_s + '%'),
        class: item_list.ready_status == 0 ? 'absolute left-1/2 transform -translate-x-1/2 text-primary dark:text-neutral' : '' %>
    </div>
  </div>
</div>

app/views/item_lists/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mx-auto pt-3 p-2 md:pl-12 py-24">
  <div class="flex justify-start items-center bg-base-100">
    <div class="flex items-center">
      <span class="material-symbols-outlined md:text-2xl text-primary" style="font-variation-settings: 'FILL' 1;">playlist_add</span>
      <h1 class="text-base md:text-lg font-medium ml-3"><%= t('.title') %></h1>
    </div>
  </div>

  <% if @item_lists.present? %>
    <div class="flex flex-wrap justify-start gap-5 md:gap-10 mt-6 md:mt-12">
      <%= render @item_lists %>
    </div>
  <% else %>
    <p class="text-center text-sm md:text-base text-gray-500 m-12">持ち物リストが見つかりませんでした</p>
  <% end %>
</div>
<button class="fixed bottom-28 right-4 md:right-20 z-60 bg-gradient-to-t from-primary to-cyan-500 text-white font-bold
  rounded-full text-base md:text-lg p-5 md:p-6 flex items-center justify-center shadow transition-all duration-300 hover:brightness-110"
  onclick="document.getElementById('addItemList').showModal()">
  <span class="material-symbols-outlined text-2xl">add</span>
</button>

<dialog id="addItemList" class="modal">
  <div class="modal-box bg-slate-50 w-96 mx-auto flex flex-col items-center py-12 dark:bg-base-200">
    <%= form_with model: @item_list, url: item_lists_path, local: true do |f| %>
      <label class="form-control w-full max-w-xs">
        <input type="text" placeholder="リストの名前" name="item_list[name]" class="input input-bordered w-full max-w-xs dark:bg-base-200" required />
      </label>
      <div class="mt-4">
        <%= f.submit '決定', class: "btn btn-primary w-full" %>
      </div>
    <% end %>
    <div class="modal-action">
      <form method="dialog">
        <button class="btn btn-ghost">キャンセル</button>
      </form>
    </div>
  </div>
</dialog>

app/views/item_lists/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="flex mx-auto pt-3 p-2 md:pl-12 py-24">
  <div class="container flex flex-col justify-start items-center md:w-1/2 md:ml-12 gap-4 w-full">
    <div class="flex justify-between items-center mx-auto w-full">
      <h1 class="text-base md:text-lg font-medium text-center"><%= @item_list.name %></h1>
      <div class="md:hidden ml-auto">
        <span class="material-symbols-outlined size-30 text-primary dark:text-neutral mt-2 mr-4" onclick="openItemModal()">edit_square</span>
        <dialog id="itemModal" class="modal md:hidden">
          <div class="modal-box bg-slate-50 w-96 mx-auto px-4 dark:bg-base-200">
            <div class="px-4 py-12 flex flex-col justify-center w-full space-y-8">
              <%= link_to new_item_list_item_path(@item_list), class: "btn w-full btn-outline text-primary font-normal bg-slate-50 dark:bg-base-200 dark:text-neutral border-primary dark:border-neutral hover:bg-gray-100 hover:border-primary hover:text-primary dark:hover:bg-base-300 dark:hover:border-neutral dark:hover:text-neutral" do %>
                <span class="material-symbols-outlined">checklist</span>
                アイテムを編集
              <% end %>
              <%= link_to item_list_quantities_path(@item_list), class: "btn w-full btn-outline text-primary font-normal bg-slate-50 dark:bg-base-200 dark:text-neutral border-primary dark:border-neutral hover:bg-gray-100 hover:border-primary hover:text-primary dark:hover:bg-base-300 dark:hover:border-neutral dark:hover:text-neutral" do %>
                <span class="material-symbols-outlined">exposure_plus_1</span>
                アイテム数を変更
              <% end %>
              <%= form_with url: clear_checked_items_item_list_path(@item_list), method: :patch, local: true, class: "w-full" do %>
                <button type="submit" class="btn w-full btn-outline text-primary font-normal bg-slate-50 dark:bg-base-200 dark:text-neutral border-primary dark:border-neutral hover:bg-gray-100 hover:border-primary hover:text-primary dark:hover:bg-base-300 dark:hover:border-neutral dark:hover:text-neutral">
                  <span class="material-symbols-outlined">refresh</span>
                  準備済みのアイテムをクリア
                </button>
              <% end %>
              <button class="filter-checked-button btn w-full btn-outline text-primary font-normal bg-slate-50 dark:bg-base-200 dark:text-neutral border-primary dark:border-neutral hover:bg-gray-100 hover:border-primary hover:text-primary dark:hover:bg-base-300 dark:hover:border-neutral dark:hover:text-neutral"
                onclick="document.getElementById('itemModal').close()">
                <span class="filter-icon material-symbols-outlined">visibility_off</span>
                <span class="filter-text">準備済みのアイテムを非表示</span>
              </button>
              <button class="btn w-full btn-ghost" onclick="document.getElementById('itemModal').close()">キャンセル</button>
            </div>
          </div>
        </dialog>
      </div>
    </div>
    <div class="flex flex-col justify-center items-center mx-auto mt-4 gap-4 w-full">
      <%= render "item_lists/ready_status", item_list: @item_list, id: dom_id(@item_list, :ready_status) %>
      <% if @selected_default_items.empty? && @selected_original_items.empty? %>
        <div class="w-full">
          <p class="text-gray-500 mt-8 text-left">持ち物を追加しましょう！</p>
        </div>
      <% else %>
        <div class="w-full" data-controller="sortable" data-sortable-url="<%= item_list_path(@item_list) %>">
          <ul data-sortable-target="list" class="w-full p-0 mt-6 space-y-4">
            <% (@selected_default_items + @selected_original_items)
                .sort_by { |item| item.item_statuses.find_by(item_list_id: @item_list.id)&.position || 0 }
                .each do |item| %>
              <li data-item-id="<%= item.id %>" class="flex items-center gap-2">
                <span class="material-symbols-outlined cursor-move drag-handle text-base-300">drag_handle</span>
                <%= render "item_statuses/item_status", item_status: item.item_statuses.find_by(item_list_id: @item_list.id) %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= hidden_field_tag :item_ids, "", id: "sortable-item-ids" %>
    </div>
  </div>

  <!-- md以上はメニュー表示 -->
  <div class="hidden md:flex flex-col w-96 my-auto bg-base-100 p-6 rounded shadow dark:bg-base-200 md:ml-20 mt-24">
    <div class="flex flex-col w-full space-y-8">
      <%= link_to new_item_list_item_path(@item_list),
        class: "btn btn-outline text-primary font-normal bg-base-100 dark:bg-base-200 dark:text-neutral border-primary dark:border-neutral hover:bg-gray-100 hover:border-primary hover:text-primary
        dark:hover:bg-base-300 dark:hover:border-neutral dark:hover:text-neutral w-full" do %>
        <span class="material-symbols-outlined">checklist</span>
        アイテムを編集
      <% end %>
      <%= link_to item_list_quantities_path(@item_list),
        class: "btn btn-outline text-primary font-normal bg-base-100 dark:bg-base-200 dark:text-neutral border-primary dark:border-neutral hover:bg-gray-100 hover:border-primary hover:text-primary
        dark:hover:bg-base-300 dark:hover:border-neutral dark:hover:text-neutral w-full" do %>
        <span class="material-symbols-outlined">exposure_plus_1</span>
        アイテム数を変更
      <% end %>
      <%= form_with url: clear_checked_items_item_list_path(@item_list), method: :patch, local: true do %>
        <button type="submit" class="btn btn-outline text-primary font-normal bg-base-100 dark:bg-base-200 dark:text-neutral border-primary dark:border-neutral hover:bg-gray-100 hover:border-primary hover:text-primary
        dark:hover:bg-base-300 dark:hover:border-neutral dark:hover:text-neutral w-full">
          <span class="material-symbols-outlined">refresh</span>
          準備済みのアイテムをクリア
        </button>
      <% end %>
      <button class="filter-checked-button btn btn-outline text-primary font-normal bg-base-100 dark:bg-base-200 dark:text-neutral border-primary dark:border-neutral hover:bg-gray-100 hover:border-primary hover:text-primary
        dark:hover:bg-base-300 dark:hover:border-neutral dark:hover:text-neutral w-full gap-4">
        <span class="filter-icon material-symbols-outlined">visibility_off</span>
        <span class="filter-text">準備済みのアイテムを非表示</span>
      </button>
    </div>
  </div>
</div>