config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :recommends do
    get "place/:place", to: "recommends#by_place", as: "by_place", on: :collection
  end

  resources :item_lists do
    resources :items, only: %i[new create update destroy] do
      post :new_original_item, on: :collection
      delete "destroy_original_item/:id", action: :destroy_original_item, as: :destroy_original_item
    end
    resources :quantities, only: %i[index edit update]

    post :duplicate, on: :member
    patch :clear_checked_items, on: :member
    patch :update_position, on: :member
  end

  resources :bag_contents do
    get :search, on: :collection
  end

  resources :item_statuses, only: %i[update] do
    patch :toggle, on: :member
    patch :sort, on: :member
  end

  resource :profile, only: %i[show edit update]

  resources :bookmarks, only: %i[index create destroy]

  get "form", to: "static_pages#form", as: "inquiry_form"
  get "policy", to: "static_pages#policy", as: "privacy_policy"
  get "terms", to: "static_pages#terms", as: "terms"
  get "how_to_use", to: "static_pages#how_to_use", as: "how_to_use"

  get "images/ogp.png", to: "images#ogp", as: "images_ogp"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/recommend.rb
class Recommend < ApplicationRecord
  belongs_to :user, foreign_key: :user_uuid
  has_many :bookmarks, as: :bookmarkable, dependent: :destroy

  validates :place, presence: true, length: { maximum: 255 }
  validates :item, presence: true, length: { maximum: 255 }
  validates :body, length: { maximum: 65_535 }

  mount_uploader :item_image, ItemImageUploader
  mount_uploader :ogp, OgpUploader

  def image_path
    if self.item_image.present?
      Rails.env.production? ? self.item_image.url : self.item_image.path
    else
      nil
    end
  end
end

app/controllers/recommends_controller.rb
class RecommendsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index by_place show]
  helper_method :prepare_meta_tags

  def index
    @recommends = Recommend.order(created_at: :desc).group_by(&:place)
  end

  def by_place
    @place = params[:place]
    @recommends = Recommend.where(place: @place)
  end

  def show
    @recommend = Recommend.find_by(uuid: params[:id])
    prepare_meta_tags(@recommend)
  end

  def new
    @recommend = Recommend.new
  end

  def create
    @recommend = current_user.recommends.build(recommend_params)
    if @recommend.save
      redirect_to recommend_path(@recommend), notice: t("defaults.flash_message.created", item: Recommend.model_name.human)
    else
      flash.now[:alert] = t("defaults.flash_message.not_created", item: Recommend.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recommend = current_user.recommends.find_by(uuid: params[:id])
  end

  def update
    @recommend = current_user.recommends.find_by(uuid: params[:id])
    if @recommend.update(recommend_params)
      redirect_to recommend_path(@recommend), notice: t("defaults.flash_message.updated", item: Recommend.model_name.human)
    else
      flash.now[:alert] = t("defaults.flash_message.not_updated", item: Recommend.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    recommend = current_user.recommends.find_by(uuid: params[:id])
    recommend.destroy!
    redirect_to recommends_path, notice: t("defaults.flash_message.deleted", item: Recommend.model_name.human), status: :see_other
  end

  private

  def prepare_meta_tags(recommend)
    image_url = OgpCreator.build(recommend.item, recommend.place, recommend.user.name, recommend: recommend)

    set_meta_tags og: {
                    site_name: "All Ready",
                    title: "#{recommend.item} | All Ready",
                    type: "website",
                    url: request.original_url,
                    image: image_url,
                    locale: "ja-JP"
                  },
                  twitter: {
                    card: "summary_large_image",
                    site: "@kumateq",
                    image: image_url
                  }
  end

  def recommend_params
    params.require(:recommend).permit(:place, :item, :body, :item_image, :item_image_cache)
  end
end

app/views/recommends/_bookmark.html.erb
<%= link_to bookmarks_path(bookmarkable: recommend), id: "bookmark-button-for-recommend-#{recommend.uuid}", data: { turbo_method: :post } do %>
  <span class="material-symbols-outlined text-primary dark:text-neutral">bookmark</span>
<% end %>

app/views/recommends/_bookmark_buttons.html.erb
<div>
  <% if current_user && current_user.bookmark?(recommend) %>
    <%= render 'unbookmark', { recommend: recommend } %>
  <% else %>
    <%= render 'bookmark', { recommend: recommend } %>
  <% end %>
</div>

app/views/recommends/_form.html.erb
<%= form_with model: @recommend, class: "space-y-4 bg-slate-50 dark:bg-base-200" do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div>
    <div class="flex items-start">
      <%= f.label :place, class: "block text-sm font-medium" %>
      <span class="text-accent ml-1">*</span>
    </div>
    <%= f.text_field :place, class: "w-full border border-gray-300 bg-slate-50 rounded-md shadow-sm px-3 py-2 focus:outline-none focus:ring-1 focus:ring-blue-500 dark:bg-base-200" %>
  </div>
  <div>
    <div class="flex items-start">
      <%= f.label :item, class: "block text-sm font-medium mb-1" %>
      <span class="text-accent ml-1">*</span>
    </div>
    <%= f.text_field :item, class: "w-full border border-gray-300 bg-slate-50 rounded-md shadow-sm px-3 py-2 focus:outline-none focus:ring-1 focus:ring-blue-500 dark:bg-base-200" %>
  </div>
  <div>
    <%= f.label :body, class: "block text-sm font-medium mb-2" %>
    <%= f.text_area :body, placeholder: "購入場所、価格帯、おすすめポイントなど", class: "w-full border border-gray-300 bg-slate-50 rounded-md shadow-sm px-3 py-2 focus:outline-none focus:ring-1 focus:ring-blue-500 dark:bg-base-200 placeholder:text-xs", rows: 5 %>
  </div>
  <div>
    <%= f.file_field :item_image, class: "file-input file-input-bordered file-input-primary file-input-sm w-full mt-2 mb-4 dark:file-input-secondary", accept: 'image/*', id: 'recommend_item_image' %>
    <%= f.hidden_field :item_image_cache %>
    <img id="recommend_image_preview" src="#" style="display:none; max-width: 200px;" />
  </div>
  <div class="flex mt-4 justify-end">
    <%= f.submit submit_label, class: "btn btn-primary w-full mt-4" %>
  </div>
<% end %>

app/views/recommends/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(bookmarkable: recommend)), id: "unbookmark-button-for-recommend-#{recommend.uuid}", data: { turbo_method: :delete } do %>
  <span class="material-symbols-outlined text-primary dark:text-neutral" style="font-variation-settings: 'FILL' 1;">bookmark</span>
<% end %>

app/views/recommends/by_place.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mx-auto pt-3 p-2 md:pl-12 py-24">
  <h1 class="text-base md:text-lg font-medium mb-6 md:mb-12"><%= @place %>のマストアイテム</h1>
  <div class="flex flex-wrap justify-start gap-5 md:gap-10">
    <% if @recommends.present? %>
      <% @recommends.each do |recommend| %>
        <%= link_to recommend_path(recommend), class: "card bg-slate-50 w-40 h-40 md:w-60 md:h-60 shadow rounded relative overflow-hidden flex items-center justify-center dark:bg-base-200" do %>
          <% if recommend.item_image? %>
            <%= image_tag recommend.item_image_url, class: "absolute inset-0 w-full h-full object-contain opacity-40" %>
          <% end %>
          <div class="relative z-10 text-center px-3">
            <h2 class="text-sm md:text-lg font-bold"> <%= recommend.item %></h2>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <p class="text-center text-sm md:text-base text-gray-500">マストアイテムが見つかりませんでした</p>
    <% end %>
  </div>
  <%= link_to new_recommend_path,
    class: "fixed bottom-28 right-4 md:right-20 z-60 bg-gradient-to-t from-primary to-cyan-500 text-white font-bold
    rounded-full text-base md:text-lg p-5 md:p-6 flex items-center justify-center shadow transition-all duration-300 hover:brightness-110" do %>
    <span class="material-symbols-outlined text-2xl">add</span>
  <% end %>
</div>

app/views/recommends/edit.html.erb
<% content_for(:title, t('.title')) %>
  <div class="flex items-center justify-center p-5">
    <div class="max-w-xl w-full mx-auto bg-slate-50 p-6 rounded shadow dark:bg-base-200">
      <div class="flex items-center space-x-4">
        <h1 class="text-lg font-medium mb-6"><%= t('.title') %></h1>
      </div>
      <%= render 'form', recommend: @recommend, submit_label: I18n.t('recommends.edit.submit_label') %>
      <% if user_signed_in? && current_user.own?(@recommend) %>
        <%= link_to t('recommends.delete.submit_label'), recommend_path(@recommend), id: "button-delete-#{@recommend.uuid}", data: {turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm')}, class: "p-2 btn btn-base-300 w-full mt-4 dark:btn-outline" %>
      <% end %>
    </div>
  </div>

app/views/recommends/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mx-auto pt-3 p-2 md:pl-12 py-24">
  <div class="flex justify-start items-center bg-base-100">
    <div class="flex items-center">
      <span class="material-symbols-outlined md:text-2xl text-primary" style="font-variation-settings: 'FILL' 1;">lightbulb_2</span>
      <h1 class="text-base md:text-lg font-medium ml-3"><%= t('.title') %></h1>
    </div>
  </div>
  <div class="flex flex-wrap justify-start gap-6 md:gap-10 mt-6 md:mt-12">
    <% if @recommends.present? %>
      <% @recommends.each do |place, recommends| %>
        <div class="card shadow rounded p-5 md:p-7 flex flex-col w-full max-w-lg bg-slate-50 dark:bg-base-200">
          <%= link_to by_place_recommends_path(place), class: "block h-full" do %>
            <h2 class="text-sm md:text-lg font-medium text-center"><%= place %></h2>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p class="text-center text-sm md:text-base text-gray-500 m-12">マストアイテムが見つかりませんでした</p>
    <% end %>
  </div>
</div>
<%= link_to new_recommend_path, class: "fixed bottom-28 right-4 md:right-20 z-60 
  bg-gradient-to-t from-primary to-cyan-500 text-white font-bold rounded-full text-base md:text-lg p-5 md:p-6 flex items-center 
  justify-center shadow transition-all duration-300 hover:brightness-110" do %>
  <span class="material-symbols-outlined text-2xl">add</span>
<% end %>

app/views/recommends/new.html.erb
<% content_for(:title, t('.title')) %>
  <div class="flex items-center justify-center p-5">
    <div class="max-w-xl w-full mx-auto bg-slate-50 p-6 rounded shadow dark:bg-base-200">
      <div class="flex items-center space-x-4">
        <h1 class="text-base md:text-lg font-medium mb-2 md:mb-6"><%= t('.title') %></h1>
      </div>
      <%= render 'form', recommend: @recommend, submit_label: I18n.t('recommends.new.submit_label') %>
    </div>
  </div>

app/views/recommends/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="flex flex-col items-center p-5">
  <div class="flex items-center w-full md:w-2/3 justify-between">
    <div class="card bg-slate-50 w-full shadow rounded p-6 dark:bg-base-200">
      <div class="flex flex-col">
        <div class="text-base md:text-lg mb-4"><%= "#{@recommend.item}" %></div>

        <div class="flex items-center gap-2 mb-4 justify-start">
          <%= image_tag @recommend.user.avatar_url, class: "w-6 h-6 rounded-full mr-2" %>
          <span class="text-xs md:text-sm"><%= @recommend.user.name %></span>
        </div>

        <div class="mt-4 text-xs md:text-sm">
          <%= simple_format(@recommend.body) %>
        </div>

        <% if @recommend.item_image? %>
          <div class="flex justify-start">
            <%= image_tag @recommend.item_image_url, class: "h-52 md:h-80 w-auto object-contain rounded shadow mt-8" %>
          </div>
        <% end %>
      </div>
      <div class="flex justify-between items-center mt-6">
        <%= link_to by_place_recommends_path(@recommend.place), class: "flex items-center md:gap-2 text-sm text-nowrap mb-1" do %>
          <span class="material-symbols-outlined text-primary dark:text-neutral">arrow_back_ios_new</span>
          もどる
        <% end %>
        <div class="flex justify-end items-center gap-5">
          <% twitter_share_url = "https://twitter.com/intent/tweet?url=#{request.url}&text=#{CGI.escape(@recommend.place)}のマストアイテム：#{CGI.escape(@recommend.item)}%0A%0A&hashtags=#{CGI.escape('AllReadyApp')}" %>
          <%= link_to twitter_share_url, target: '_blank' do %>
            <button class="flex items-center gap-2 px-2 py-1 mb-1 bg-gray-100 text-gray-800 text-sm font-medium rounded hover:bg-gray-200 dark:bg-gray-100 dark:hover:bg-gray-200" type="button">
              <div class="w-[15px] h-[15px]"> 
                <svg viewBox="0 0 1200 1227" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" class="w-full h-full fill-black">
                  <path d="M714.163 519.284L1160.89 0H1055.03L667.137 450.887L357.328 0H0L468.492 681.821L0 1226.37H105.866L515.491 750.218L842.672 1226.37H1200L714.137 519.284H714.163ZM569.165 687.828L521.697 619.934L144.011 79.6944H306.615L611.412 515.685L658.88 583.579L1055.08 1150.3H892.476L569.165 687.854V687.828Z" />
                </svg>
              </div>
              <span>ポスト</span>
            </button>
          <% end %>
          <%= render 'bookmark_buttons', { recommend: @recommend } %>
          <% if user_signed_in? && current_user.own?(@recommend) %>
            <%= link_to edit_recommend_path(@recommend), id: "button-edit-#{@recommend.uuid}" do %>
              <span class="material-symbols-outlined text-primary dark:text-neutral">edit</span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>